image: 'maven:3-jdk-8'
stages:
  - test
  - build
services:
  - 'mysql:5.5'
  - 'mongo:3.4-jessie'
variables:
  MYSQL_DATABASENAME: "userDb"
  MYSQL_URL: "jdbc:mysql://mysql/cricUserDb?createDatabaseIfNotExist=true"
  MYSQL_USERNAME: "root"
  MYSQL_PASSWORD: "root"
  MYSQL_ROOT_PASSWORD: "root"
  MONGO_DATABASENAME: "cricdb"
  MONGO_HOST: "mongo"
  MONGO_PORT: "27017"
cache:
  paths:
    - .m2/repository
    -  target
maven-test:
  stage: test
  script: "mvn test"
maven-build:
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - target/*.jar
